# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/aliya/OneDrive/Masats/final_project_1/final_project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/aliya/OneDrive/Masats/final_project_1/final_project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/aliya/OneDrive/Masats/final_project_1/final_project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/aliya/OneDrive/Masats/final_project_1/final_project_1.srcs/sources_1/new/final_project_1.vhd
  {C:/Users/aliya/OneDrive/Masaüstü/csd/CSD - zeynep/laab7_2/laab7_2.srcs/sources_1/imports/Lab4 2/freq_div.vhd}
  C:/Users/aliya/OneDrive/Masaüstü/FSM_LAB_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/aliya/Downloads/Basys-3-Master1/Basys-3-Master.xdc
set_property used_in_implementation false [get_files C:/Users/aliya/Downloads/Basys-3-Master1/Basys-3-Master.xdc]


synth_design -top FSM_LAB_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef FSM_LAB_top.dcp

catch { report_utilization -file FSM_LAB_top_utilization_synth.rpt -pb FSM_LAB_top_utilization_synth.pb }
